version: 2
updates:
  - package-ecosystem: npm
    directory: 'src/ui/ide'
    schedule: 
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: 'src/ui/pos'
    schedule: 
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: gomod
    directory: 'src/svc/gateway-store'
    schedule: 
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: gomod
    directory: 'src/svc/gateway-web'
    schedule: 
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: gomod
    directory: 'src/svc/pkg'
    schedule: 
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
