version: 2
updates:
  - package-ecosystem: npm
    directory: 'src/ui/ide'
    schedule: 
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 10
    versioning-strategy: increase
