version: '3.8'

services:
  ide-ui:
    image: node:16.5
    volumes:
      - ${PWD}/src/ui/ide:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 3000:3000
  pos-ui:
    image: node:16.5
    volumes:
      - ${PWD}/src/ui/pos:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 3001:3000
  gateway:
    image: gateway
    build:
      context: src/svc/gateway
