name: Gateway-Store CI

on:
  pull_request:
    paths:
      - 'src/svc/gateway-store/**'
      - Makefile
      - .github/workflows/gateway-store.yaml
      - .github/workflows/reusable-svc.yaml
  push:
    branches: [master]
    paths:
      - 'src/svc/gateway-store/**'
      - Makefile
      - .github/workflows/gateway-store.yaml
      - .github/workflows/reusable-svc.yaml
    
jobs:
  docker:
        uses: briand787b/ncx-infra/.github/workflows/reusable-helm.yaml@master
        with:
          svc-name: gateway-store
        secrets:
          gcloud-token: ${{ secrets.GCLOUD_TOKEN }}