name: Gateway-Store CI

on:
  pull_request:
    paths:
      - 'src/svc/gateway-store/**'
      - Makefile
      - .github/workflows/gateway-store.yaml
      - .github/workflows/reusable-svc.yaml
  push:
    branches: [master]
    paths:
      - 'src/svc/gateway-store/**'
      - Makefile
      - .github/workflows/gateway-store.yaml
      - .github/workflows/reusable-svc.yaml
    
jobs:
  docker:
        uses: briand787b/ncx/.github/workflows/reusable-svc.yaml@master
        with:
          svc-name: gateway-store
        secrets:
          git-access-token: ${{ secrets.GIT_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}