name: Gateway-Web CI

on:
  pull_request:
    paths:
      - 'src/svc/gateway-web/**'
      - Makefile
      - .github/workflows/gateway-web.yaml
      - .github/workflows/reusable-svc.yaml
      - 'src/svc/pkg'
  push:
    branches: [master]
    paths:
      - 'src/svc/gateway-web/**'
      - Makefile
      - .github/workflows/gateway-web.yaml
      - .github/workflows/reusable-svc.yaml
      - 'src/svc/pkg'
    
jobs:
  docker:
        uses: briand787b/ncx/.github/workflows/reusable-svc.yaml@master
        with:
          svc-name: gateway-web
        secrets:
          git-access-token: ${{ secrets.GIT_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}