name: PoS CI

on:
  pull_request:
    paths:
      - 'src/ui/pos/**'
      - Makefile
      - docker-compose.yaml
      - .github/workflows/pos.yaml
  push:
    branches: [master]
    paths:
      - 'src/ui/pos/**'
      - Makefile
      - docker-compose.yaml
      - .github/workflows/pos.yaml
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build
        name: Build Production Docker Image
        run: make build-pos

      - name: Docker Build Status
        if: steps.build.outcome == 'failure'
        run: exit 1

      - name: Publish Production Docker Image
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: make push-pos

  # TODO: Make this reusable
  infra:
    needs: docker
    # TODO: UNCOMMENT THIS CODE WHEN FINISHED PLAYING WITH CI/CD
    # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      NCX_APP: pos
    steps:
      - name: Add SHORT_SHA Env Var
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Clone Infra Repo
        uses: actions/checkout@v3
        with:
          repository: 'briand787b/ncx-infra'
      - name: Update IaC Image Tag
        run: |
          sed -i 's/tag:.*$/tag: '"$SHORT_SHA"'/g' charts/ncx-$NCX_APP/values.yaml
          cat charts/ncx-pos/values.yaml
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Automatic pull request
      - name: Push Changes to IaC Repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update container for production release ncx-$NCX_APP $SHORT_SHA"
          git pull --rebase https://github.com/briand787b/ncx-infra master
          git push origin master