name: PoS CI

on:
  pull_request:
    paths:
      - 'src/ui/pos/**'
      - Makefile
      - docker-compose.yaml
      - .github/workflows/pos.yaml
  push:
    branches: [master]
    paths:
      - 'src/ui/pos/**'
      - Makefile
      - docker-compose.yaml
      - .github/workflows/pos.yaml
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build
        name: Build Production Docker Image
        run: make build-pos

      - name: Docker Build Status
        if: steps.build.outcome == 'failure'
        run: exit 1

      - name: Publish Production Docker Image
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: make push-pos

  update-infra:
    needs: docker
    # TODO: UNCOMMENT THIS CODE WHEN FINISHED PLAYING WITH CI/CD
    # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Clone Infra Repo
        uses: actions/checkout@v3
        with:
          repository: 'briand787b/ncx-infra'

      - name: Checkout Feature Branch
        run: git checkout -b release-pos-${{ GITHUB_SHA }}