name: Pull Request for IDE Against Master

on:
  pull_request:
    branches: [master]
    paths:
      - 'src/ui/ide/**'

jobs:
  production-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the PRODUCTION Docker image
        run: make build-ide
  local-dev-build:
    # this doesn't actually do anything, but it would be a good place to run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the DEVELOPMENT Docker image
        run: docker-compose build ide
