name: Push IDE Changes to Master

on:
  push:
    branches: [master]
    paths:
      - 'src/ui/ide/**'
      - Makefile
      - docker-compose.yaml
    
jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish the PRODUCTION Docker image
        run: |
          make build-ide
          make push-ide
